
[theme]
primaryColor = "#F63366"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"
font = "sans serif"
base = "dark"

[server]
enableXsrfProtection = false
enableCORS = false
    